export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const TOGGLE_LOAD = 'TOGGLE_LOAD';
export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO';
export const GET_USER_INFOS = 'GET_USER_INFOS';

export const GET_PATIENTS = 'GET_PATIENTS';
export const SELECT_PATIENT = 'SELECT_PATIENT';
export const SELECT_PATIENT_FROM_TOP_MENU = 'SELECT_PATIENT_FROM_TOP_MENU';
